title: HiveMQ MQTT Client
description: A fast, asynchronous, reactive mqtt client library
logo: assets/images/hivemq-mqtt-client-neg.svg
version: 1.2.2
android_retrofix_version: 0.3.6
android_retrostreams_version: 1.7.2

remote_theme: pmarsceill/just-the-docs@654da0a
color_scheme: dark

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: false
  button: true

aux_links:
  "News":
    - "https://hivemq.github.io/hivemq-mqtt-client/news"
  "GitHub":
    - "https://github.com/hivemq/hivemq-mqtt-client"
# site.github.repository_url
# site.github.releases_url
# site.github.issues_url

permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-redirect-from

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
