title: HiveMQ MQTT Client
description: A fast, asynchronous, reactive mqtt client library
logo: assets/images/hivemq-mqtt-client-neg.svg
version: 1.2.2
android_retrofix_version: 0.3.6
android_retrostreams_version: 1.7.2

remote_theme: SgtSilvio/just-the-docs@98dc323f
color_scheme: dark

permalink: pretty

just_the_docs:
  collections:
    html_pages:
      root_path: docs/

defaults:
  - scope:
      path: "docs"
      type: pages
    values:
      layout: default

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: false
  button: true

aux_links:
  "News":
    - "https://hivemq.github.io/hivemq-mqtt-client/news"
  "GitHub":
    - "https://github.com/hivemq/hivemq-mqtt-client"
# site.github.repository_url
# site.github.releases_url
# site.github.issues_url

plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-redirect-from

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [ ]
  blanklines: false
  profile: false
